app:
  name: forum
  port: 8000
  replicaCount: 2
  image:
    repository: forum
    tag: "latest"
  db_type: postgresql

db:
  name: forum-db
  replicaCount: 1
  image:
    repository: postgres
    tag: "latest"
  port: 5432
  storage:
    size: 2Gi
    className: manual
    accessMode: ReadWriteMany
