apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  labels:
    app: {{ .Values.app.name }}
data:
  WHICH_DB: {{ .Values.app.db_type | quote | default "postgresql" }}
  FORUM_DB_NAME: {{ .Values.db.name | quote }}
  FORUM_DB_HOST: {{ .Values.db.name | quote }}
  FORUM_DB_PORT: {{ .Values.db.port | quote | default "5432" }}
