apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: WHICH_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: WHICH_DB
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: FORUM_DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: FORUM_DB_HOST
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: FORUM_JWT_SECRET
            - name: JWT_ALG
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: FORUM_JWT_ALG
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: FORUM_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: FORUM_DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}
