apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  replicas: {{ .Values.db.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
        - name: {{ .Values.db.name }}
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: FORUM_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: FORUM_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: FORUM_DB_PASSWORD
          volumeMounts:
            - name: {{ .Values.db.name }}-volume-mount
              mountPath: /var/lib/postgresql/
      volumes:
        - name: {{ .Values.db.name }}-volume-mount
          persistentVolumeClaim:
            claimName: {{ .Values.db.name }}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.name }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.name }}-pvc
  labels:
    app: {{ .Values.db.name }}
    type: local
spec:
  storageClassName: {{ .Values.db.storage.className | quote | default "manual" }}
  accessModes:
    - {{ .Values.db.storage.accessMode | quote | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
  volumeName: {{ .Values.db.name }}-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.name }}-pv
  labels:
    type: local
spec:
  capacity:
    storage: {{ .Values.db.storage.size }}
  storageClassName: {{ .Values.db.storage.className | quote | default "manual" }}
  accessModes:
    - {{ .Values.db.storage.accessMode | quote | default "ReadWriteMany" }}
  hostPath:
    path: /mnt/data/{{ .Values.db.name }}
