apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  FORUM_JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
  FORUM_JWT_ALG: {{ .Values.jwtAlg | b64enc | quote }}
  FORUM_DB_USER: {{ .Values.dbUser | b64enc | quote }}
  FORUM_DB_PASSWORD: {{ .Values.dbPassword | b64enc | quote }}
